### ISSUE TITLE
EXIT CODE 127 While Building in VS (Kali environment)

### ISSUE THREAD

**Issue by z99z** [Hackplayers/Salsa-tools#2]
I have VISUAL STUDIO in kali

Tried to build both salseo loader and Evil salsa but both ended up with following error

Executing task: msbuild /property:GenerateFullPaths=true /t:build <

/bin/bash: msbuild: command not found
The terminal process command '/bin/bash -c 'msbuild /property:GenerateFullPaths=true /t:build'' failed to launch (exit code: 127)

Terminal will be reused by tasks, press any key to close it.

**Comment by cybervaca** [comment]
You should use windows to compile it. From linux you can get to compile the loader but not the evilsalsa. Use windows, greetings.
